### ISSUE TITLE
Any plans for 3.1 support? 

### ISSUE THREAD

**Issue by Devolv** [vvasabi/phpbb3-emoji#2]
I tried your installation and was stopped at the tracks at the php modifcation , the DB collation obviously worked.

Any idea where the @mysqli_query exists in the 3.1.X? 
I realize your implementation is mostly front-end via Jquery, so It's very clever & promising to work in any version provided that the unicode information is stored correctly in mySQL.

**Comment by vvasabi** [comment]
In 3.1.6, the MySQLi database driver is located at `phpbb/db/driver/mysqli.php`. Templates appear to be at the same spot as they were in 3.0, so the template modification instructions likely will still apply.

If I eventually upgrade my phpBB installation to 3.1, I might update this repository. In the meantime, pull requests are welcome. :)

**Comment by Devolv** [comment]
Awesome.  I got it to work with the provided file path, thank you! You do need to edit the Message Parser file under `phpbb/includes/message_parser.php` and remove the UTF-8 Unsupported Character chunk of code.  I've also made a minor change to include Android in the JS code so that emoji's (native to their devices) work as well. I can create a Pull request as soon as I can.

**Comment by vvasabi** [comment]
Great! Thanks for sharing your findings.
